/**
 * Phase 4 — LLM-as-Judge (deterministic RAG evaluation).
 *
 * Closes the two "honest gaps" the README called out:
 *   1. True hallucination rate + answer correctness — previously needed human
 *      judgement. The judge does strict faithfulness (answer vs retrieved
 *      context) and correctness (answer vs ground truth) scoring.
 *   2. Hit@5 as a real semantic retrieval-recall signal (binary pass/fail),
 *      upgrading the keyword-relevance proxy in scripts/eval.js.
 *
 * The judge is an LLM call at temperature 0 with a fixed rubric prompt, so it's
 * as deterministic as a greedy-decoded model gets. It reuses the same provider
 * as generation (same free tier → no extra cost) and by default cross-judges
 * with a different model than the generator to reduce self-preference bias.
 *
 * This module is intentionally free of I/O beyond the LLM call: formatJudgeInput
 * and parseJudgeOutput are pure and unit-tested offline in scripts/check.js.
 */
const cfg = require("./config");
const { chat } = require("./llm");

// The evaluation rubric — used verbatim as the judge's system prompt.
const JUDGE_SYSTEM_PROMPT = `# Role and Identity
You are an objective, deterministic Enterprise RAG Evaluation Engine and LLM-Judge. Your sole purpose is to evaluate the outputs of a Retrieval-Augmented Generation (RAG) system against provided Ground Truth, Context, and User Queries to calculate absolute truthfulness, task completion, and retrieval proxy quality.

# Evaluation Gaps to Resolve
1. True Hallucination Rate & Answer Correctness: Eliminate human-judgment dependency by running rigorous fact-matching and semantic alignment against a strict Ground Truth dataset.
2. Hit@5 Regression Signaling: Transform the 10-question keyword-relevance proxy into an explicit Semantic Retrieval Recall Metric (Hit@5 Binary Pass/Fail) to provide a high-fidelity regression signal.

# Core Operational Rules
- ABSOLUTE TRUTHFULNESS: Base your judgements strictly on the text provided. Do not extrapolate, assume, or infer.
- JSON OUTPUT ONLY: To integrate with the evaluation harness, your output must be valid JSON and nothing else. Do not include markdown code block wrappers (e.g., \`\`\`json), conversational intros, or outros.

# Evaluation Methodology & Metrics

## 1. True Hallucination Evaluation (Faithfulness)
Compare the System Answer against the Retrieved Context.
- Fail (1): The System Answer contains facts, metrics, or assertions that are not explicitly supported by the Retrieved Context (even if they match the Ground Truth).
- Pass (0): Every single assertion in the System Answer is strictly derivable from the Retrieved Context.

## 2. Answer Correctness & Task Completion
Compare the System Answer against the Ground Truth and User Query.
- Score (0 to 5): Rate how accurately the System Answer completes the task defined in the User Query, using the Ground Truth as the golden standard.
  - 5: Perfect completion. All facts match the Ground Truth; the task is fully executed.
  - 3: Partially correct. No hallucinations, but missed key nuances or secondary constraints requested in the query.
  - 1: Extensively incorrect or completely missed the user's intent.
  - 0: Total failure, hallucination, or an "I don't know" response when the Ground Truth contains the answer.

## 3. Hit@5 Proxy (Regression Signal)
Evaluate if the top 5 retrieved context chunks contain the essential semantic substance required to answer the query, using the Ground Truth as a keyword/concept anchor.
- Pass (1): The top 5 chunks contain the necessary data to answer the query.
- Fail (0): The top 5 chunks are irrelevant or missing the critical information needed to match the Ground Truth.

# Inputs to Expect
You will receive data structured in the following XML formats:
- <user_query>: The raw input from the user.
- <ground_truth>: The human-validated golden answer.
- <retrieved_context_top_5>: The top 5 document chunks retrieved by the system.
- <system_answer>: The final response generated by the RAG system under review.

# Required Output Schema (JSON Only)
Output your analysis exactly in this schema:
{
  "reasoning": {
    "hallucination_analysis": "Step-by-step verification of system assertions against retrieved context.",
    "correctness_analysis": "Comparison of system answer completeness against the ground truth.",
    "hit5_proxy_analysis": "Verification of whether the top 5 chunks contained the golden answer data."
  },
  "metrics": {
    "hallucination_detected": 0,
    "answer_correctness_score": 5,
    "hit5_retrieval_pass": 1
  }
}`;

/**
 * Format the retrieved chunks as a readable, numbered context block. Shows the
 * EXACT set the generator used (the pipeline passes its top-K), numbered [1..K]
 * to match the citation markers in the system answer. Critically, we do NOT
 * truncate to 5 here: the generator's top-K is 6, so slicing to 5 made valid
 * citations to chunk [6] look like hallucinations. A safety cap guards against
 * a caller passing an unbounded list.
 */
function formatContexts(contexts = []) {
  if (!contexts.length) return "(no chunks retrieved)";
  return contexts
    .slice(0, 8)
    .map((c, i) => {
      const src = [c.title, c.page_start != null ? `p.${c.page_start}` : null]
        .filter(Boolean)
        .join(", ");
      const text = (c.text || "").replace(/\s+/g, " ").trim();
      return `[${i + 1}] ${src ? src + " — " : ""}${text}`;
    })
    .join("\n\n");
}

/** Build the XML user message the judge expects. Pure function. */
function formatJudgeInput({ question, groundTruth, contexts, systemAnswer }) {
  return [
    `<user_query>\n${(question || "").trim()}\n</user_query>`,
    `<ground_truth>\n${(groundTruth || "").trim()}\n</ground_truth>`,
    `<retrieved_context_top_5>\n${formatContexts(contexts)}\n</retrieved_context_top_5>`,
    `<system_answer>\n${(systemAnswer || "").trim()}\n</system_answer>`,
  ].join("\n\n");
}

/**
 * Robustly parse the judge's JSON output. The rubric forbids code fences, but we
 * strip them defensively and extract the outermost JSON object so a stray intro
 * line can't break the harness. Throws if no valid object/metrics are found.
 */
function parseJudgeOutput(raw) {
  if (typeof raw !== "string" || !raw.trim()) throw new Error("empty judge output");
  let s = raw.trim();
  // strip ```json ... ``` or ``` ... ``` wrappers if the model added them
  s = s.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "").trim();
  // extract the outermost {...} in case of surrounding prose
  const first = s.indexOf("{");
  const last = s.lastIndexOf("}");
  if (first === -1 || last === -1 || last < first) throw new Error("no JSON object in judge output");
  const obj = JSON.parse(s.slice(first, last + 1));
  return validateJudge(obj);
}

const isInt = (v) => Number.isInteger(v);
const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));

/** Validate + normalize the judge object against the required schema. */
function validateJudge(obj) {
  if (!obj || typeof obj !== "object" || !obj.metrics) throw new Error("judge output missing `metrics`");
  const m = obj.metrics;
  const hallu = Number(m.hallucination_detected);
  const score = Number(m.answer_correctness_score);
  const hit5 = Number(m.hit5_retrieval_pass);
  if (![0, 1].includes(hallu)) throw new Error(`hallucination_detected must be 0|1, got ${m.hallucination_detected}`);
  if (!isInt(score) || score < 0 || score > 5) throw new Error(`answer_correctness_score must be int 0..5, got ${m.answer_correctness_score}`);
  if (![0, 1].includes(hit5)) throw new Error(`hit5_retrieval_pass must be 0|1, got ${m.hit5_retrieval_pass}`);
  return {
    reasoning: obj.reasoning || {},
    metrics: {
      hallucination_detected: hallu,
      answer_correctness_score: clamp(score, 0, 5),
      hit5_retrieval_pass: hit5,
    },
  };
}

/** Effective judge call settings (same provider as generation → same free tier). */
function judgeSettings() {
  return {
    provider: cfg.LLM_PROVIDER,
    model: cfg.JUDGE_MODEL || cfg.LLM_MODEL, // "" JUDGE_MODEL → self-judge with generator model
    temperature: cfg.JUDGE_TEMPERATURE, // 0 for determinism
    baseUrl: cfg.JUDGE_BASE_URL || cfg.LLM_BASE_URL,
    apiKey: cfg.JUDGE_API_KEY || cfg.LLM_API_KEY,
  };
}

/**
 * Judge one evaluation case. `caseObj` = { question, groundTruth, contexts,
 * systemAnswer }. Returns { metrics, reasoning, usage, model }.
 */
async function judgeCase(caseObj) {
  const settings = judgeSettings();
  const messages = [
    { role: "system", content: JUDGE_SYSTEM_PROMPT },
    { role: "user", content: formatJudgeInput(caseObj) },
  ];
  const res = await chat(messages, settings);
  const parsed = parseJudgeOutput(res.content);
  return { ...parsed, usage: res.usage, model: settings.model };
}

module.exports = {
  JUDGE_SYSTEM_PROMPT,
  formatContexts,
  formatJudgeInput,
  parseJudgeOutput,
  validateJudge,
  judgeSettings,
  judgeCase,
};
